name: Apply

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: ./
          auto_approve: true
          variables: |
            domain_name = "test.kenbrake.com"
            bucket_name = "test.kenbrake.com"
            common_tags = {
              Project = "test.kenbrake.com"
            }
          